apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service
spec:
  selector:
    matchLabels:
      app: currency-service
  template:
    metadata:
      labels:
        app: currency-service
    spec:
      containers:
      - name: server
        image: thien0611/currency-service:latest
        ports:
        - name: grpc
          containerPort: 3040
        env:
        - name: PORT
          value: "3040"
---
apiVersion: v1
kind: Service
metadata:
  name: currency-service
spec:
  type: ClusterIP
  selector:
    app: currency-service
  ports:
  - name: grpc
    port: 3040
    targetPort: 3040
