apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: server
        image: thien0611/product-service:latest
        ports:
        - containerPort: 3050
        env:
        - name: PORT
          value: "3050"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - name: grpc
    port: 3050
    targetPort: 3050