apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-server
        image: thien0611/shipping-service:latest
        ports:
        - containerPort: 3080
        env:
        - name: PORT
          value: "3080"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  type: ClusterIP
  selector:
    app: shipping-service
  ports:
  - name: grpc
    port: 3080
    targetPort: 3080
